POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token:{{token}}

{
  "name": "张三",
  "idCard": "330101199001011111",
  "type": "1"
}
###
POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token:{{token}}

{
  "id": 1726867803677528064,
  "memberId": 1,
  "name": "李四",
  "idCard": "330101199001011111",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/query-list?page=1&size=3
Accept: application/json
token: {{token}}

###
DELETE http://localhost:8000/member/passenger/delete/1726881415431327744
Accept: application/json
token: {{token}}
