server:
  port: 8000
spring:
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" # 允许哪些网站的跨域请求
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
      routes[0]:
        id: member
        uri: http://127.0.0.1:8001
        predicates:
          - Path=/member/**
      routes[1]:
        id: business
        uri: http://127.0.0.1:8002
        predicates:
          - Path=/business/**
      routes[2]:
        id: batch
        uri: http://127.0.0.1:8003
        predicates:
          - Path=/batch/**