server:
  port: 8004
  servlet:
    context-path: /business

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: business
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: true
      time-to-live: 60s
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    local-cache-scope: statement
rocketmq:
  name-server: http://43.137.12.232:9876
  producer:
    group: default
logging:
  level:
    top.wml.train.business.mapper: trace